package com.project.audit.entity;

public enum AuditEventType {
    REGISTRATION,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGOUT,
    ROLE_CHANGE,
    DOCUMENT_UPLOAD,
    VERIFICATION_CREATED,
    VERIFICATION_COMPLETED,
    VERIFICATION_FAILED,
    INVESTIGATION_STATUS_CHANGE,
    ADMIN_ACTION
}

